config/routes.rb
Rails.application.routes.draw do
  resources :foods, only: [:index, :show, :new, :create]
  get '/', to: 'application#home', as: 'home'
  # get '/foods', to: 'foods#index', as: 'foods'
  # get '/foods/new', to: 'foods#new', as: 'new_food'
  # get '/foods/:id', to: 'foods#show', as: 'food'
  # post '/foods', to: 'foods#create'
  resources :franchises, only: [:index, :show, :new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/analytics', to: 'application#analytics', as: 'analytics'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
    belongs_to :franchise, required: false
    validates :name, presence: true
end

app/models/franchise.rb
class Franchise < ApplicationRecord
    has_many :foods
    validates :name, :costume, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def home
    end

    def analytics
        @prices = []
    end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
  end

  def show
    @food = Food.find(params[:id])
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.create(food_params)
    redirect_to food_path(@food)
  end
  private

  def food_params
    params.require(:food).permit(:name, :vegan, :protein, :description, :price)
  end
end

app/controllers/franchises_controller.rb
class FranchisesController < ApplicationController
  def index
    @franchises = Franchise.all
  end

  def show
    @franchise = Franchise.find params[:id]
  end

  def new
    @franchise = Franchise.new
  end

  def create
    @franchise = Franchise.new(franchise_params)
    if @franchise.save
      redirect_to franchise_path(@franchise)
    else
      render :new
    end
  end

  private

  def franchise_params
    params.require(:franchise).permit(:name, :costume, :food_ids => [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/franchises_helper.rb
module FranchisesHelper
end

app/views/application/analytics.html.erb
<h1>Analytics Page</h1>

<div> Total Franchises: <%= Franchise.all.count %><br>
<div> Total Foods: <%= Food.all.count %><br>
<div> Total Vegan Foods: <%= Food.where(vegan: true).count%><br>
<div> If you'd like to try them all it'll cost: <%= Food.sum(:price) %><br>

app/views/application/home.html.erb
<h3 id="welcome">Welcome to the Spider-Man food franchise!</h3>
<div>
    <img src="https://i.pinimg.com/originals/7a/63/55/7a6355f7604c03b428883231c1c70b71.png">
</div>

app/views/foods/_form.html.erb
<%= form_for @food do |f|%><br>
<%=f.label :name%><br>
<%=f.text_field :name%><br>
<%=f.label :vegan%>:
<%=f.label 'true'%>
<%=f.radio_button :vegan, true%>
<%=f.label 'false'%>
<%=f.radio_button :vegan, false%><br>
<%=f.label :protein%><br>
<%=f.text_field :protein%><br>
<%=f.label :description%><br>
<%=f.text_area :description%><br>
<%=f.label :price%><br>
<%=f.number_field :price%><br>
<%=f.submit%><br>
<%end%>

app/views/foods/index.html.erb
<h1>Foods</h1>
<% @foods.each do |f|%>
<%= f.name%><br>
<%end%>

app/views/foods/new.html.erb
<h1>Create Spectacular Spidey Food</h1>
<%= render partial: 'form' %>

app/views/foods/show.html.erb
<h1>Spider Foods</h1>
<h2> Name: <%= @food.name %><br>
Vegan: <%= @food.vegan %><br>
Protein: <%= @food.protein %><br>
Description: <%= @food.description %><br>
Price: <%= @food.price %><br><h2>

app/views/franchises/_form.html.erb
 <% @franchise.errors.any? do%>
 <div id="error_explanation">
    <h2><%= pluralize(@franchise.errors.count, "error") %> prohibited this franchise from being saved:</h2>
 
    <ul>
    <% @franchise.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_for @franchise do |f| %>
<% if @franchise.errors.any? %>
    <% @franchise.errors.full_messages.each do |error| %>
        <div><%= error %></div>
    <% end %>
<% end %><br>
<%= f.label :name %><br>
<%= f.text_field :name %><br>
<%= f.label :costume %><br>
<%= f.text_field :costume %><br>
<%= f.label "Foods" %><br>
<%= f.collection_check_boxes :food_ids, Food.all, :id, :name %><br><br>
<%= f.submit%>
<% end %>

app/views/franchises/index.html.erb
<h1>Franchises</h1>
<ul>
<% @franchises.each do |franchise| %>
<li><%= franchise.name %></li>
<% end %>
</ul>

app/views/franchises/new.html.erb
<h1>Create New Franchises</h1>
<%= render partial: "form" %>

app/views/franchises/show.html.erb
<h1>Franchises</h1>
<h2>Name: <%= @franchise.name %><br>
Spidey Costume: <%= @franchise.costume %></h2>
<% @franchise.foods.each do |food| %>
<%= food.name %><br>
<%= food.vegan %><br>
<%= food.protein %><br>
<%= food.description %><br>
<%= food.price %><br>
--------------------<br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spider Bait</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <h1>Into The Spider Eats</h1>
    <div class="links">
    <%= link_to "Home", home_path %> | 
    <%= link_to "Franchises", franchises_path %> | 
    <%= link_to "New Franchises", new_franchise_path %> | 
    <%= link_to "Foods", foods_path %> | 
    <%= link_to "New Foods", new_food_path %> |
    <%= link_to "Analytics", analytics_path %> 

    </div>
    </header>
    <%= yield %>
  </body>
</html>